#!/usr/bin/env bash
set -euo pipefail
DRY_RUN=0

log() { printf '[autodetect] %s\n' "$*"; }
warn() { printf '[autodetect][warn] %s\n' "$*" >&2; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1 ;;
    *) warn "Unknown option ignored: $1" ;;
  esac
  shift
done

run_cmd() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "DRY-RUN: $*"
    return 0
  fi
  "$@"
}

ensure_shell_hook() {
  local rc_file="$1"
  local hook='[ -f "$HOME/.config/dotfiles/session_tools.sh" ] && source "$HOME/.config/dotfiles/session_tools.sh"'
  run_cmd touch "$rc_file"
  if ! grep -Fq "$hook" "$rc_file"; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log "DRY-RUN: append shell hook to $rc_file"
    else
      {
        echo ""
        echo "# dot-files session helpers"
        echo "$hook"
      } >>"$rc_file"
    fi
  fi
}

detect_default_iface() {
  local iface
  iface="$(ip route show default 2>/dev/null | awk '{print $5; exit}')"
  if [[ -z "${iface:-}" ]]; then
    iface="$(ip -o link show | awk -F': ' '{print $2}' | grep -Ev '^(lo|docker|br-|veth|virbr|zt|tailscale)' | head -n1 || true)"
  fi
  echo "${iface:-eth0}"
}

detect_default_source() {
  local src
  if command -v pactl >/dev/null 2>&1; then
    src="$(pactl info 2>/dev/null | awk -F': ' '/Default Source/ {print $2; exit}')"
  else
    src=""
  fi
  echo "${src:-default}"
}

detect_display_manager() {
  local dm_link dm
  dm_link="$(readlink -f /etc/systemd/system/display-manager.service 2>/dev/null || true)"
  dm="$(basename "${dm_link:-}" .service)"
  if [[ -z "${dm:-}" || "$dm" == "display-manager" ]]; then
    for candidate in sddm gdm lightdm ly greetd; do
      if systemctl is-enabled "${candidate}.service" >/dev/null 2>&1 || systemctl is-active "${candidate}.service" >/dev/null 2>&1; then
        echo "$candidate"
        return
      fi
    done
    echo "unknown"
    return
  fi
  echo "$dm"
}

detect_lock_manager() {
  if command -v hyprlock >/dev/null 2>&1; then
    echo "hyprlock"
  elif command -v swaylock >/dev/null 2>&1; then
    echo "swaylock"
  elif command -v gtklock >/dev/null 2>&1; then
    echo "gtklock"
  elif command -v i3lock >/dev/null 2>&1; then
    echo "i3lock"
  else
    echo "loginctl"
  fi
}

detect_gpu_vendor() {
  if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
    echo "nvidia"
    return
  fi
  if lspci 2>/dev/null | grep -Eqi 'vga|3d|display' && lspci 2>/dev/null | grep -Eqi 'amd|advanced micro devices|radeon'; then
    if lsmod 2>/dev/null | grep -q '^amdgpu'; then
      echo "amd"
      return
    fi
  fi
  if lsmod 2>/dev/null | grep -q '^i915'; then
    echo "intel"
    return
  fi
  echo "unknown"
}

find_dri_card_for_pci_bdf() {
  local bdf="$1"
  local bypath="/dev/dri/by-path/pci-${bdf}-card"
  if [[ -e "$bypath" ]]; then
    readlink -f "$bypath" || true
  fi
}

find_gpu_card_path() {
  local vendor="$1"
  local bdf=""
  case "$vendor" in
    nvidia)
      bdf="$(lspci -Dnn 2>/dev/null | awk '/NVIDIA/ && /(VGA|3D|Display|display|controller)/{print $1; exit}')"
      ;;
    amd)
      bdf="$(lspci -Dnn 2>/dev/null | awk '/AMD|Advanced Micro Devices|Radeon/ && /(VGA|3D|Display|display|controller)/ {print $1; exit}')"
      ;;
    intel)
      bdf="$(lspci -Dnn 2>/dev/null | awk '/Intel/ && /(VGA|3D|Display|display|controller)/ {print $1; exit}')"
      ;;
  esac
  [[ -n "${bdf:-}" ]] || return 0
  find_dri_card_for_pci_bdf "$bdf"
}

write_hypr_gpu_overrides() {
  local gpu_vendor="$1"
  local out_file="$HOME/.config/hypr/UserConfigs/ENVariables.local.conf"
  local aq_line=""
  local primary_card=""
  local other_card=""

  primary_card="$(find_gpu_card_path "$gpu_vendor" || true)"
  if [[ -n "$primary_card" ]]; then
      if [[ -e /dev/dri/card0 && "/dev/dri/card0" != "$primary_card" ]]; then
        other_card="/dev/dri/card0"
      elif [[ -e /dev/dri/card1 && "/dev/dri/card1" != "$primary_card" ]]; then
        other_card="/dev/dri/card1"
      fi
      if [[ -n "$other_card" ]]; then
        aq_line="env = AQ_DRM_DEVICES,${primary_card}:${other_card}"
      else
        aq_line="env = AQ_DRM_DEVICES,${primary_card}"
      fi
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "DRY-RUN: would write $out_file (gpu_vendor=$gpu_vendor)"
    return 0
  fi

  mkdir -p "$(dirname "$out_file")"
  {
    echo "# Auto-generated by dot-files post_install_autodetect.sh"
    echo "# Do not edit manually; re-run autodetect instead."
    case "$gpu_vendor" in
      nvidia)
        echo "env = LIBVA_DRIVER_NAME,nvidia"
        echo "env = __GLX_VENDOR_LIBRARY_NAME,nvidia"
        echo "env = NVD_BACKEND,direct"
        echo "env = GSK_RENDERER,ngl"
        ;;
      amd)
        echo "env = LIBVA_DRIVER_NAME,radeonsi"
        echo "env = AMD_VULKAN_ICD,RADV"
        ;;
      intel)
        echo "env = LIBVA_DRIVER_NAME,iHD"
        ;;
      *)
        echo "# Unknown GPU vendor; no vendor-specific env overrides applied."
        ;;
    esac
    if [[ -n "$aq_line" ]]; then
      echo "$aq_line"
    fi
  } >"$out_file"
}

write_monitor_config_if_available() {
  local out_file="$HOME/.config/hypr/monitors.conf"
  local tmp_json
  tmp_json="$(mktemp)"

  if ! command -v hyprctl >/dev/null 2>&1; then
    rm -f "$tmp_json"
    return
  fi
  if ! hyprctl -j monitors >"$tmp_json" 2>/dev/null; then
    rm -f "$tmp_json"
    return
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "DRY-RUN: would update $out_file from hyprctl monitor data"
    rm -f "$tmp_json"
    return
  fi

  if ! python3 - "$tmp_json" "$out_file" <<'PY'
import json
import pathlib
import sys
json_path = pathlib.Path(sys.argv[1])
out_path = pathlib.Path(sys.argv[2])
try:
    data = json.loads(json_path.read_text())
except Exception:
    sys.exit(1)
lines = [
    "# Auto-generated by dot-files post_install_autodetect.sh",
    "# Re-run: bash ~/dot-files/scripts/post_install_autodetect.sh",
]
for mon in data:
    name = mon.get("name")
    width = mon.get("width")
    height = mon.get("height")
    refresh = mon.get("refreshRate")
    x = mon.get("x", 0)
    y = mon.get("y", 0)
    scale = mon.get("scale", 1.0)
    transform = mon.get("transform", 0)
    if not name or not width or not height or refresh is None:
      continue
    lines.append(f"monitor={name},{width}x{height}@{refresh:.2f},{x}x{y},{scale}")
    if transform:
      lines.append(f"monitor={name},transform,{transform}")
if len(lines) > 2:
    out_path.write_text("\n".join(lines) + "\n")
PY
  then
    warn "Unable to generate monitor config from hyprctl output"
  fi

  rm -f "$tmp_json"
}

patch_waybar_iface() {
  local iface="$1"
  local user_modules="$HOME/.config/waybar/UserModules"
  if [[ -f "$user_modules" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log "DRY-RUN: patch TRAFFIC_IFACE in $user_modules to $iface"
    else
      sed -i -E "s/TRAFFIC_IFACE=[^[:space:]]+/TRAFFIC_IFACE=${iface}/g" "$user_modules"
    fi
  fi
}

patch_voice_source() {
  local source_name="$1"
  local keybinds="$HOME/.config/hypr/configs/Keybinds.conf"
  if [[ -f "$keybinds" ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log "DRY-RUN: patch VOICE_SOURCE in $keybinds to $source_name"
    else
      sed -i -E "s/VOICE_SOURCE=[^[:space:]']+/VOICE_SOURCE=${source_name}/g" "$keybinds"
    fi
  fi
}

main() {
  local iface source_name dm lock_mgr gpu_vendor
  iface="$(detect_default_iface)"
  source_name="$(detect_default_source)"
  dm="$(detect_display_manager)"
  lock_mgr="$(detect_lock_manager)"
  gpu_vendor="$(detect_gpu_vendor)"

  run_cmd mkdir -p "$HOME/.config/dotfiles"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log "DRY-RUN: write $HOME/.config/dotfiles/autodetect.env"
  else
    cat >"$HOME/.config/dotfiles/autodetect.env" <<EOF
DOTFILES_DEFAULT_IFACE=$iface
DOTFILES_VOICE_SOURCE=$source_name
DOTFILES_DISPLAY_MANAGER=$dm
DOTFILES_LOCK_MANAGER=$lock_mgr
DOTFILES_GPU_VENDOR=$gpu_vendor
DOTFILES_LAST_DETECT=$(date -Iseconds)
EOF
  fi

  patch_waybar_iface "$iface"
  patch_voice_source "$source_name"
  write_monitor_config_if_available
  write_hypr_gpu_overrides "$gpu_vendor"

  ensure_shell_hook "$HOME/.bashrc"
  ensure_shell_hook "$HOME/.zshrc"

  log "Detected interface: $iface"
  log "Detected voice source: $source_name"
  log "Detected display manager: $dm"
  log "Detected lock manager: $lock_mgr"
  log "Detected GPU vendor: $gpu_vendor"
}

main "$@"
